// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/telemetry.proto
//
// NOTE: This file is hand-written to match the proto schema since protoc
// is not available in this dev environment. The Dockerfile regenerates
// this from proto/telemetry.proto during the build.

package pb

// OrderSubmitted is the Intent event — generated before sending the HTTP
// request to the contestant's exchange server.
type OrderSubmitted struct {
	TimestampUs    int64   `protobuf:"varint,1,opt,name=timestamp_us,json=timestampUs,proto3" json:"timestamp_us,omitempty"`
	SubmissionId   string  `protobuf:"bytes,2,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	BotId          int32   `protobuf:"varint,3,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	OrderId        string  `protobuf:"bytes,4,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Action         string  `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	Side           string  `protobuf:"bytes,6,opt,name=side,proto3" json:"side,omitempty"`
	Ticker         string  `protobuf:"bytes,7,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Price          float64 `protobuf:"fixed64,8,opt,name=price,proto3" json:"price,omitempty"`
	Quantity       int32   `protobuf:"varint,9,opt,name=quantity,proto3" json:"quantity,omitempty"`
	CancelTargetId uint64  `protobuf:"varint,10,opt,name=cancel_target_id,json=cancelTargetId,proto3" json:"cancel_target_id,omitempty"`
	Seq               uint64 `protobuf:"varint,11,opt,name=seq,proto3" json:"seq,omitempty"`
	ContestantOrderId uint64 `protobuf:"varint,12,opt,name=contestant_order_id,json=contestantOrderId,proto3" json:"contestant_order_id,omitempty"`
	EndOfRun          bool   `protobuf:"varint,13,opt,name=end_of_run,json=endOfRun,proto3" json:"end_of_run,omitempty"`
}

// TradeExecuted is the Observation event — generated by parsing the HTTP
// response. One per individual trade match (unrolled from trades[]).
type TradeExecuted struct {
	TimestampUs        int64   `protobuf:"varint,1,opt,name=timestamp_us,json=timestampUs,proto3" json:"timestamp_us,omitempty"`
	SubmissionId       string  `protobuf:"bytes,2,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	BotId              int32   `protobuf:"varint,3,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	ContestantOrderId  uint64  `protobuf:"varint,4,opt,name=contestant_order_id,json=contestantOrderId,proto3" json:"contestant_order_id,omitempty"`
	MatchedOrderId     uint64  `protobuf:"varint,5,opt,name=matched_order_id,json=matchedOrderId,proto3" json:"matched_order_id,omitempty"`
	ExecutionPrice     float64 `protobuf:"fixed64,6,opt,name=execution_price,json=executionPrice,proto3" json:"execution_price,omitempty"`
	ExecutionQuantity  int32   `protobuf:"varint,7,opt,name=execution_quantity,json=executionQuantity,proto3" json:"execution_quantity,omitempty"`
	Ticker             string  `protobuf:"bytes,8,opt,name=ticker,proto3" json:"ticker,omitempty"`
	AggressorOrderId   string  `protobuf:"bytes,9,opt,name=aggressor_order_id,json=aggressorOrderId,proto3" json:"aggressor_order_id,omitempty"`
	Seq                uint64  `protobuf:"varint,10,opt,name=seq,proto3" json:"seq,omitempty"`
}

// MetricsBatch is the aggregated latency/throughput metrics from one thread.
type MetricsBatch struct {
	TimestampMs  int64   `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	SubmissionId string  `protobuf:"bytes,2,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	ThreadId     int32   `protobuf:"varint,3,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	Http_200     int64   `protobuf:"varint,4,opt,name=http_200,json=http200,proto3" json:"http_200,omitempty"`
	Http_4Xx     int64   `protobuf:"varint,5,opt,name=http_4xx,json=http4xx,proto3" json:"http_4xx,omitempty"`
	Http_5Xx     int64   `protobuf:"varint,6,opt,name=http_5xx,json=http5xx,proto3" json:"http_5xx,omitempty"`
	Timeout      int64   `protobuf:"varint,7,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Econnref     int64   `protobuf:"varint,8,opt,name=econnref,proto3" json:"econnref,omitempty"`
	OtherErr     int64   `protobuf:"varint,9,opt,name=other_err,json=otherErr,proto3" json:"other_err,omitempty"`
	AvgLatencyMs float64 `protobuf:"fixed64,10,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	Samples      int64   `protobuf:"varint,11,opt,name=samples,proto3" json:"samples,omitempty"`
	Histogram    []int64 `protobuf:"varint,12,rep,packed,name=histogram,proto3" json:"histogram,omitempty"`
}

// AuditBatch is the 500ms flush payload from one C++ thread.
type AuditBatch struct {
	Orders  []*OrderSubmitted `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	Trades  []*TradeExecuted  `protobuf:"bytes,2,rep,name=trades,proto3" json:"trades,omitempty"`
	Metrics *MetricsBatch     `protobuf:"bytes,3,opt,name=metrics,proto3" json:"metrics,omitempty"`
}

// StreamTelemetryResponse is the server's ack at the end of the stream.
type StreamTelemetryResponse struct {
	BatchesReceived int64  `protobuf:"varint,1,opt,name=batches_received,json=batchesReceived,proto3" json:"batches_received,omitempty"`
	Status          string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}
